#!/bin/sh
echo "Installing UN20 server application"
cd /data
rm -f index.tar
gunzip index.tar.gz
tar xv -f index.tar
cp /data/lib/secugenun202015.cfg5 /data
chmod +x start-index-un20
chmod +x InitScript
chmod +x index-un20app
echo "UN20 server application installed"
