#!/bin/sh
echo "Installing UN20 server application"
cd /data
gunzip index.tar.gz
tar xv -f index.tar
chmod +x start-index-un20
chmod +x InitScript
chmod +x index-un20app
echo "UN20 server application installed"
