#!/bin/sh
echo "Starting UN20 server application"
if [ -e /data/un20-debug ]; then
echo "UN20 debug enabled"
/data/index-un20app /dev/ttyS1 debug
else
/data/index-un20app /dev/ttyS1
fi
# when the app exits we need to halt
if [ -e /data/no-shutdown ]; then
echo "Shutdown inhibited by /data/no-shutdown"
else
echo "Requesting system to shutdown"
/sbin/halt
fi
