
install:
	@echo "copying secugen libraries..."
	adb push libsgfdu05.so /usr/lib
	adb push libsgfpamx.so /usr/lib
	adb push libsgfplib.so /usr/lib
	adb push secugenun202015.cfg5 /data
	@echo "copying secugen libraries done."

